apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: "relay-1-{{ .Values.services.cardano.config.CARDANO_NETWORK }}"
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - "relay-1-{{ .Values.services.cardano.config.CARDANO_NETWORK }}"
  routes:
    - match: HostSNI(`*`)
      services:
        - name: "{{ $.Chart.Name }}-cardano-relay-1-service"
          namespace: {{ .Values.namespace }}
          port: {{ .Values.services.cardano.config.NODE_PORT }}
