export enum VARIABLES {
    BUDGETS = 'bs',
    CHALLENGES = 'cs',
    COHORT = 'co',
    FUNDS = 'fs',
    FUNDED_PROPOSALS = 'fp',
    OPENSOURCE_PROPOSALS = 'op',
    FUNDING_STATUS = 'f',
    GROUPS = 'g',
    MIN_BUDGET = 1,
    MAX_BUDGET = 4000000,
    PAGE = 'p',
    PER_PAGE = 'l',
    PEOPLE = 'pp',
    QUICKPITCHES = 'qp',
    STATUS = 'ss',
    TRACKER_ID_MONTHLY_REPORT = 'HSH9YZDM',
    TRACKER_ID_PA = 'GQ56QFBJ',
    TRACKER_ID_GROUPS = 'UD6WDUFD',
    TRACKER_ID_PEOPLE = 'TVTZ9W9Z',
    TRACKER_ID_PROPOSALS = 'RPZTGJL8',
    TYPE = 't',
    SEARCH = 's',
    SORTS = 'st',
    TAGS = 'ts',
}
