export enum VARIABLES {
    BUDGETS = 'bs',
    CHALLENGES = 'cs',
    COHORT = 'co',
    FUNDS = 'fs',
    FUNDED_PROPOSALS = 'fp',
    FUNDING_STATUS = 'f',
    GROUPS = 'g',
    MIN_BUDGET = 1,
    MAX_BUDGET = 2000000,
    PEOPLE = 'pp',
    STATUS = 'ss',
    TYPE = 't',
    SEARCH = 's',
    SORTS = 'st',
    TAGS = 'ts',
}
