apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ $.Chart.Name }}-activevoteplans"
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: shared-volume
              emptyDir: {}
          initContainers:
            - name: fetch-archive
              image: registry.lidonation.com/lidonation/lidonation/jormungandr:fund10
              volumeMounts:
                - name: shared-volume
                  mountPath: /VOLUME_ROOT
              command: ["/bin/sh", "-c",
                "LATEST_ARCHIVE_ID_FROM_LIDO=$(curl -s https://www.lidonation.com/api/catalyst-explorer/ledger-snapshots/latest | jq -r '.data.snapshot_id') && \
                URL=$(curl -s https://archiver.projectcatalyst.io/api/v1/archives/$LATEST_ARCHIVE_ID_FROM_LIDO/download | jq -r .url) && \
                curl -o /VOLUME_ROOT/archive.tar.zstd \"$URL\" && \
                zstd -d /VOLUME_ROOT/archive.tar.zstd && tar -xvf /VOLUME_ROOT/archive.tar && \
                rm -f /VOLUME_ROOT/archive.tar.zstd /VOLUME_ROOT/archive.tar && mkdir /VOLUME_ROOT/persist && mkdir /VOLUME_ROOT/persist/leader-1/ && \
                mv /VOLUME_ROOT/artifacts /VOLUME_ROOT/persist/leader-1/"]
          containers:
            - name: query-api
              image: bitnami/kubectl:1.24.9-debian-11-r10
              volumeMounts:
                - name: shared-volume
                  mountPath: /VOLUME_ROOT
              command: ["/bin/sh", "-c"]
              args:
                - sleep 10m
                - curl http://127.0.0.1:10000/api/v0/vote/active/plans
                - if [[ $? -ne 0 ]]; then
                    echo "Failed to get the active vote plans."
                    exit 1
                  fi
                - curl http://127.0.0.1:10000/api/v0/vote/active/plans > /VOLUME_ROOT/activevoteplans.json
          restartPolicy: Never
