kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.namespace }}-search-pvc"
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 4Gi
