apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $.Chart.Name }}-ingress"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
  annotations:
    {{- range $key, $value := .Values.services.web.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  {{- range .Values.services.web.ingress.tls }}
    - hosts:
    {{- range .hosts }}
      - {{ . }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  rules:
    {{- range .Values.services.web.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Chart.Name }}-nginx-service"
                port:
                  number: 8080
    {{- end }}