apiVersion: v1
stringData:
  APP_KEY: {{ .Values.services.web.secret.app_key }}
  DEEPL_AUTH_KEY: {{ .Values.services.web.secret.DEEPL_AUTH_KEY }}
  MAIL_USERNAME: {{ .Values.services.web.secret.MAIL_USERNAME }}
  MAIL_PASSWORD: {{ .Values.services.web.secret.MAIL_PASSWORD }}
  MEILISEARCH_KEY: {{ .Values.services.web.secret.MEILISEARCH_KEY }}
  POSTGRESQL_DB_SYNC_PASSWORD: {{ .Values.services.dbsync.db.secret.POSTGRESQL_PASSWORD }}
  POSTGRESQL_WEB_PASSWORD: {{ .Values.services.web_db.secret.POSTGRESQL_PASSWORD }}
  REDIS_PASSWORD: {{ .Values.services.redis.secret.REDIS_PASSWORD }}  
  RECAPTCHA_V3_SECRET_KEY: {{ .Values.services.web.secret.RECAPTCHA_V3_SECRET_KEY }}
  RECAPTCHA_V3_SITE_KEY: {{ .Values.services.web.secret.RECAPTCHA_V3_SITE_KEY }}  
  STRIPE_SK: {{ .Values.services.web.secret.STRIPE_SK }}
  STRIPE_PK: {{ .Values.services.web.secret.STRIPE_PK }}
  TWITTER_CONSUMER_SECRET: {{ .Values.services.web.secret.TWITTER_CONSUMER_SECRET }}
  TWITTER_CONSUMER_KEY: {{ .Values.services.web.secret.TWITTER_CONSUMER_KEY }}
  TWITTER_ACCESS_TOKEN_SECRET: {{ .Values.services.web.secret.TWITTER_ACCESS_TOKEN_SECRET }}
  TWITTER_ACCESS_TOKEN: {{ .Values.services.web.secret.TWITTER_ACCESS_TOKEN }}
  TWITTER_BEARER_TOKEN: {{ .Values.services.web.secret.TWITTER_BEARER_TOKEN }}
  TWITTER_OAUTH_CLIENT_ID: {{ .Values.services.web.secret.TWITTER_OAUTH_CLIENT_ID }}
  TWITTER_OAUTH_CLIENT_SECRET: {{ .Values.services.web.secret.TWITTER_OAUTH_CLIENT_SECRET }}
  TWITTER_OAUTH_CALLBACK_URL: {{ .Values.services.web.secret.TWITTER_OAUTH_CALLBACK_URL }}
  ZOOM_CLIENT_KEY: {{ .Values.services.web.secret.zoom_api_key }}
  ZOOM_CLIENT_SECRET: {{ .Values.services.web.secret.zoom_api_secret }}
kind: Secret
metadata:
  name: "{{ $.Chart.Name }}-secrets"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
type: Opaque