apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-fpm-service"
  namespace: {{ .Values.namespace }}
  labels:
    service: "{{ $.Chart.Name }}-fpm"
spec:
  ports:
    - port: 9000
      name: fpm
      targetPort: fpm
      protocol: TCP
  selector:
    service: "{{ $.Chart.Name }}-fpm"
