apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-nginx-service"
  namespace: {{ .Values.namespace }}
  labels:
    service: "{{ $.Chart.Name }}-nginx"
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: http
  selector:
    service: "{{ $.Chart.Name }}-nginx"
