apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-search-service"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}-search"
spec:
  ports:
    - port: 7700
      name: search
      protocol: TCP
      targetPort: meilisearch
  selector:
    app: "{{ $.Chart.Name }}-search"
