apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ $.Chart.Name }}-ncdb"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      service: "{{ $.Chart.Name }}-ncdb"
  serviceName: "{{ $.Chart.Name }}-ncdb-service"
  replicas: 1
  template:
    metadata:
      labels:
        service: "{{ $.Chart.Name }}-ncdb"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ncdb
          image: nocodb/nocodb:0.105.3
          env:
            - name: NC_REDIS_URL
              value: {{ .Values.services.ncdb.redisUrl }}
            - name: NC_INVITE_ONLY_SIGNUP
              value: "Yes"
            - name: DB_QUERY_LIMIT_DEFAULT
              value: "100"
            - name: NC_MIGRATIONS_DISABLED
              value: "yes"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
                  optional: false
          resources:
            limits:
              memory: 4096Mi
              cpu: 2
            requests:
              cpu: 50m
              memory: 1024Mi
          ports:
            - containerPort: 8080
              name: ncdb
          volumeMounts:
            - name: "{{ $.Chart.Name }}-ncdb-pv"
              mountPath: /usr/app/data
              readOnly: false
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
  volumeClaimTemplates:
    - metadata:
        name: "{{ $.Chart.Name }}-ncdb-pv"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 20Gi