apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ $.Chart.Name }}-search"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: "{{ $.Chart.Name }}-search"
  serviceName: "{{ $.Chart.Name }}-search-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ $.Chart.Name }}-search"
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: "{{ $.Chart.Name }}-search-pv"
          persistentVolumeClaim:
            claimName: "{{ .Values.namespace }}-search-pvc"
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.1.1
          resources:
            limits:
              memory: 12288Mi
              cpu: 5
            requests:
              cpu: 600m
              memory: 2048Mi
          envFrom:
            - secretRef:
                name: "{{ $.Chart.Name }}-search-secret"
          env:
            - name: MEILI_ENV
              value: "production"
            - name: MEILI_LOG_LEVEL
              value: 'WARN'
            - name: MEILI_MAX_INDEXING_MEMORY
              value: '8192Mb'
            - name: MEILI_MAX_INDEXING_THREADS
              value: '3'
          ports:
            - containerPort: 7700
              name: meilisearch
          volumeMounts:
            - name: "{{ $.Chart.Name }}-search-pv"
              mountPath: /meili_data/data.ms
              readOnly: false
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}