apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $.Chart.Name }}-ingress"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
  annotations:
    {{- range $key, $value := .Values.services.submitApi.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:  
    - hosts:
      - {{ .Values.services.submitApi.ingress.host }}
      secretName: {{ .Values.services.submitApi.ingress.tls.secretName }}    
  rules:
    - host: {{ .Values.services.submitApi.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Chart.Name }}-service"
                port:
                  number: 8080