{{- if eq .Values.services.cardano.config.CARDANO_NETWORK "mainnet" -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: "tx-{{ .Values.services.cardano.config.CARDANO_NETWORK }}"
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - "tx-{{ .Values.services.cardano.config.CARDANO_NETWORK }}"
  routes:
    - match: HostSNI(`*`)
      services:
        - name: "{{ $.Chart.Name }}-service"
          namespace: {{ .Values.namespace }}
          port: {{ .Values.services.cardano.config.SUBMIT_TX_PORT }}
{{- end -}}