apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP      
      targetPort: http      
  selector:
    app: "{{ $.Chart.Name }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-relay-service"
  namespace: {{ .Values.namespace }}
  labels:
    app:  "{{ $.Chart.Name }}"
spec:
  sessionAffinity: ClientIP
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.services.cardano.config.SUBMIT_TX_PORT }}
      targetPort: {{ .Values.services.cardano.config.SUBMIT_TX_PORT }}
      name: submittx
    - port: 12798
      targetPort: 12798
      name: prometheus
    - port: 30111
      targetPort: 30111
      name: ipc
  selector:
    app: "{{ $.Chart.Name }}"