apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $.Chart.Name }}-cardano-configmap"
  labels:
    name: "{{ $.Chart.Name }}-cardano-configmap"
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.services.cardano.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
