apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $.Chart.Name }}-cardano-configurations-configmap"
  labels:
    name: "{{ $.Chart.Name }}-cardano-configurations-configmap"
  namespace: {{ .Values.namespace }}
data:
  config.json: |-
  {{- .Values.configurationFiles.config | nindent 4}}
  config.producer.json: |-
  {{- .Values.configurationFiles.configProducer | nindent 4}}
  config.relay2.json: |-
  {{- .Values.configurationFiles.configRelay2 | nindent 4}}
  config.tx.json: |-
  {{- .Values.configurationFiles.configTx | nindent 4}}
  topology.producer.json: |-
  {{- .Values.configurationFiles.topology.producer | nindent 4}}
  topology.relay.json: |-
  {{- .Values.configurationFiles.topology.relay | nindent 4}}
  topology.relay2.json: |-
  {{- .Values.configurationFiles.topology.relay2 | nindent 4}}
  topology.submittx.json: |-
  {{- .Values.configurationFiles.topology.submittx | nindent 4}}
