apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ $.Chart.Name }}-fortuna"
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 900
      parallelism: 1
      backoffLimit: 5
      template:
        spec:
          shareProcessNamespace: true
          restartPolicy: OnFailure
          volumes:
            - name: seedphrase
              secret:
                secretName: "{{ $.Chart.Name }}-secret"
          containers:
            - name: fortuna
              image: "{{ .Values.services.fortuna.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 2000m
                  memory: 512Mi
                limits:
                  cpu: 9000m
                  memory: 2048Mi
              command:
                - /bin/sh
                - -c
                - deno task cli mine
              lifecycle:
                postStart:
                  exec:
                    command: [ "/bin/sh", "-c", "cp /tmp/seed.txt /app/seed.txt && cp /tmp/seed.txt /app/miner/seed.txt" ]
              volumeMounts:
                - name: seedphrase
                  readOnly: true
                  mountPath: "/tmp"
              env:
                - name: KUPO_URL
                  value: http://lidolovelace-cardano-kupo-service.lidolovelace.svc.cluster.local:1442
                - name: OGMIOS_URL
                  value: wss://ogmios-mainnet-api-goaskada-com-e2b526.us1.demeter.run
#                  value: ws://lidolovelace-cardano-ogmios-service.lidolovelace.svc.cluster.local:1337
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret }}