apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Chart.Name }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
    service: "{{ $.Chart.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ $.Chart.Name }}"
      service: "{{ $.Chart.Name }}"
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "{{ $.Chart.Name }}"
        service: "{{ $.Chart.Name }}"
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      volumes:
        - name: node-configurations
          configMap:
            name: "lidolovelace-cardano-configurations-configmap"
        - name: node-ipc
          emptyDir: {}
      containers:
      - name: app
        image: "{{ .Values.services.ogmios.image.repository }}:{{ .Values.services.ogmios.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: ogmios
            containerPort: 1337
            protocol: TCP
        args: [
            "--host", "0.0.0.0",
            "--node-socket", "/ipc/node.socket",
            "--node-config", "/tmp/config/config.json"
        ]
        resources:
          limits:
            memory: 2048Mi
            cpu: 300
          requests:
            cpu: 100m
            memory: 256Mi
        env:
          - name: CARDANO_NODE_PORT
            value: "{{ .Values.services.cardano.config.NODE_PORT }}"
        volumeMounts:
          - name: node-ipc
            mountPath: /ipc
            readOnly: false
      - name: ipc
        image: alpine/socat:1.7.4.4
        env:
        - name: CARDANO_NODE_SOCKET_TCP_HOST
          value: "lidolovelace-cardano-producer-service"
        - name: CARDANO_NODE_SOCKET_TCP_PORT
          value: "30111"
        - name: SOCAT_TIMEOUT
          value: "3600"
        command: [
            "sh",
            "-c",
            "socat UNIX-LISTEN:/ipc/node.socket,fork TCP:${CARDANO_NODE_SOCKET_TCP_HOST}:${CARDANO_NODE_SOCKET_TCP_PORT},ignoreeof"
        ]
        volumeMounts:
        - mountPath: /ipc
          name: node-ipc
          readOnly: false