FROM php:8.2-fpm-alpine3.17

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/v3.17/main" >> /etc/apk/repositories \
    && apk upgrade -U -a \
    && apk add -Uuv \
    autoconf \
    bash \
    chromium \
    ffmpeg \
    fcgi \
    font-noto-emoji \
    freetype \
    freetype-dev \
    gifsicle \
    gcc \
    g++ \
    git \
    harfbuzz \
    imagemagick \
    imagemagick-dev \
    jpegoptim \
    libstdc++ \
    libtool \
    libjpeg-turbo-dev \
    libzip-dev \
    libpng-dev \
    make \
    netcat-openbsd \
    postgresql-dev \
    pcre-dev \
    nginx \
    nodejs \
    npm \
    nss \
    optipng \
    pngquant \
    postgresql-client \
    supervisor \
    ttf-freefont \
    wqy-zenhei \
    && rm -rf /var/cache/apk/*

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/ \
    PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser"

# Download and install composer
COPY --from=composer:2.3 /usr/bin/composer /usr/bin/composer

RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include

RUN docker-php-ext-install -j$(nproc) pdo pdo_pgsql pdo_mysql mysqli pgsql opcache pcntl gd bcmath posix zip exif intl

RUN printf "\n" | pecl install redis imagick && docker-php-ext-enable redis imagick

RUN npm install --global --unsafe-perm puppeteer

RUN apk del autoconf g++ libtool make pcre-dev

COPY ./docker/start-container /usr/local/bin/start-container
COPY ./opt /opt
COPY ./etc /etc
COPY ./usr /usr

# RUN  wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1tSt8GXQ3veQ7I0UjJhZgqIIm-MgptVwA' -O /opt/cardano-cli && chmod a+x /opt/cardano-cli

# Install PHP extensions
RUN chmod a+x /opt/install-extensions.sh /opt/entrypoint.sh \
    && chmod a+x /opt/php-fpm-healthcheck \
    && mkdir -p /run/nginx \
    && /opt/install-extensions.sh


RUN chmod +x /usr/local/bin/start-container

#COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./docker/php.ini /etc/php/8.1/cli/conf.d/99-sail.ini
WORKDIR /var/www/html
EXPOSE 8000

ENTRYPOINT start-container