FROM php:8.2-fpm-alpine3.18

ARG GITHUB_PACKAGE_REGISTRY_TOKEN

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/v3.18/main" >> /etc/apk/repositories \
    && apk add -Uuv --no-cache \
    autoconf \
    bash \
    chromium \
    ffmpeg \
    fcgi \
    font-noto-emoji \
    freetype \
    freetype-dev \
    gifsicle \
    gcc \
    g++ \
    git \
    harfbuzz \
    imagemagick \
    imagemagick-dev \
    jpegoptim \
    libstdc++ \
    libtool \
    libjpeg-turbo-dev \
    libzip-dev \
    libpng-dev \
    make \
    netcat-openbsd \
    postgresql-dev \
    pcre-dev \
    nginx \
    nodejs \
    npm \
    nss \
    optipng \
    pngquant \
    postgresql-client \
    supervisor \
    ttf-freefont \
    wqy-zenhei \
    && rm -rf /var/cache/apk/*

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/ \
    PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser" \
    GITHUB_PACKAGE_REGISTRY_TOKEN=${GITHUB_PACKAGE_REGISTRY_TOKEN}

# Download and install composer
COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include

RUN docker-php-ext-install -j$(nproc) pdo pdo_pgsql pdo_mysql mysqli pgsql opcache pcntl gd bcmath posix zip exif intl

RUN printf "\n" | pecl install redis imagick && docker-php-ext-enable redis imagick

COPY ./opt /opt
COPY ./etc /etc
COPY ./usr /usr

# Install PHP extensions
RUN chmod a+x /opt/install-extensions.sh /opt/entrypoint.sh \
    && /opt/install-extensions.sh

WORKDIR /var/www/html
EXPOSE 8000