apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
spec:
  ports:
    - port: 80
      name: kupo
      protocol: TCP      
      targetPort: kupo      
  selector:
    app: "{{ $.Chart.Name }}"