apiVersion: v1
stringData:
  BLOCKFROST_PROJECT_ID: {{ .Values.services.lucid.secret.blockfront_project_id }}
kind: Secret
metadata:
  name: "{{ $.Chart.Name }}-secrets"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
type: Opaque