{{- if eq .Values.services.cardano.config.CARDANO_NETWORK "main" -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.namespace }}-relay2-ipc-pv"
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server-svc.atlas-raddcreative-io.svc.cluster.local
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.namespace }}-relay2-ipc-pvc"
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Mi
{{- end -}}