{{- if eq .Values.services.cardano.config.CARDANO_NETWORK "main" -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-cardano-relay-2-service"
  namespace: {{ .Values.namespace }}
  labels:
    app:  "{{ $.Chart.Name }}-cardano-relay-2"
spec:
  sessionAffinity: ClientIP
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.services.cardano.config.RELAY2_PORT }}
      targetPort: {{ .Values.services.cardano.config.RELAY2_PORT }}
      name: crelay2
    - port: 12798
      targetPort: 12798
      name: prometheus
  selector:
    app: "{{ $.Chart.Name }}-cardano-relay-2"
{{- end -}}
