apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-cardano-producer-service"
  namespace: {{ .Values.namespace }}
  labels:
    app:  "{{ $.Chart.Name }}-cardano-producer"
spec:
  sessionAffinity: ClientIP
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.services.cardano.config.NODE_PORT }}
      targetPort: {{ .Values.services.cardano.config.NODE_PORT }}
      name: cproducer
    - port: 12798
      targetPort: 12798
      name: prometheus
  selector:
    app: "{{ $.Chart.Name }}-cardano-producer"
