apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-cardano-relay-1-service"
  namespace: {{ .Values.namespace }}
  labels:
    app:  "{{ $.Chart.Name }}-cardano-relay-1"
spec:
  sessionAffinity: ClientIP
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.services.cardano.config.NODE_PORT }}
      targetPort: {{ .Values.services.cardano.config.NODE_PORT }}
      name: crelay1
    - port: 12798
      targetPort: 12798
      name: prometheus
    - port: 30111
      targetPort: 30111
      name: ipc
  selector:
    app: "{{ $.Chart.Name }}-cardano-relay-1"