#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
  case "$CONTAINER_ROLE" in
    queue | q)
      /usr/bin/php -d variables_order=EGPCS /var/www/html/artisan horizon
      ;;
    scheduler | s)
      while [ true ]
      do
        php /var/www/html/artisan schedule:run --verbose --no-interaction &
        sleep 60
      done
      ;;
    app | a)
      /usr/bin/php -d variables_order=EGPCS -d max_execution_time=300 /var/www/html/artisan serve --host=0.0.0.0 --port=80
      ;;
    *)
      echo 'this container has no role... it is a sitting duck doing nothing!'
      echo 'Please $CONTAINER_ROLE to either queue, scheduler, or app'
      ;;
  esac
fi
