apiVersion: v1
stringData:
  POSTGRESQL_DATABASE: {{ .Values.services.dbsync.db.secret.POSTGRESQL_DB }}
  POSTGRESQL_PASSWORD: {{ .Values.services.dbsync.db.secret.POSTGRESQL_PASSWORD }}
  POSTGRESQL_POSTGRES_PASSWORD: {{ .Values.services.dbsync.db.secret.POSTGRESQL_POSTGRES_PASSWORD }}
  postgresql-db: {{ .Values.services.dbsync.db.secret.POSTGRESQL_DB }}
  postgresql-username: {{ .Values.services.dbsync.db.secret.POSTGRESQL_USERNAME }}
  postgresql-password: {{ .Values.services.dbsync.db.secret.POSTGRESQL_POSTGRES_PASSWORD }}
  POSTGRESQL_USERNAME: {{ .Values.services.dbsync.db.secret.POSTGRESQL_USERNAME }}
kind: Secret
metadata:
  name: "{{ $.Chart.Name }}-postgres-secrets"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}-postgres"
type: Opaque
