apiVersion: v1
stringData:
  postgres_db: {{.Values.services.dbsync.db.secret.POSTGRESQL_DB}}
  postgres_user: {{ .Values.services.dbsync.db.secret.POSTGRESQL_USERNAME }}
  postgres_password: {{ .Values.services.dbsync.db.secret.POSTGRESQL_PASSWORD }}
kind: Secret
metadata:
  name: "{{ $.Chart.Name }}-secrets"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
type: Opaque
